### ISSUE TITLE
OPSIN error messages lost when parsing fails

### ISSUE THREAD

**Issue by rytheranderson** [JacksonBurns/py2opsin#12]
Great repo, simple and useful!

OPSIN outputs a helpful error message when parsing fails. For example, when trying to parse "Methane is an IUPAC name" via `java -jar opsin-cli-2.7.0-jar-with-dependencies.jar` I get:
```
Methane is an IUPAC name is unparsable due to the following being uninterpretable: is an IUPAC name The following was not parseable: is an IUPAC name
```
Nice, it tells me where parsing starts to not work. However, running the same string with `py2opsin` I just get the empty string:
```python
>>> from py2opsin import py2opsin
>>> py2opsin("Methane is an IUPAC name")
''
```
As errors are sent to `subprocess.DEVNULL` (inconvenient to access there). I'm not sure what the best way to address this is with the current design, but using `subprocess.Popen` with `stderr=PIPE` and then calling `process.communicate(input=temp_f)` would preserve any error messages.

**Comment by JacksonBurns** [comment]
Thanks for the kind words!

I think this would make a great addition. We didn't think of it when first built it.

I've incorporated your notes here in a branch and will open a PR shortly. I'll grab all of the OPSIN parsing errors and throw them into a python warning, that way those who want to ignore them can still do so.

Thanks for the suggestion!

**Comment by JacksonBurns** [comment]
[`py2opsin v1.0.3`](https://github.com/JacksonBurns/py2opsin/releases/tag/v1.0.3) is now on PyPI and it includes these improvements :tada:! Thanks again for the suggestion @rytheranderson!

**Comment by rytheranderson** [comment]
Cool, thanks @JacksonBurns!
